<?php
declare(strict_types=1);

// HikingTrailClosures SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

HikingTrailClosuresUtility::setRegistrar(function (HikingTrailClosuresUtility $u): void {
    $u->clean = [HikingTrailClosuresClean::class, 'call'];
    $u->done = [HikingTrailClosuresDone::class, 'call'];
    $u->make_error = [HikingTrailClosuresMakeError::class, 'call'];
    $u->feature_add = [HikingTrailClosuresFeatureAdd::class, 'call'];
    $u->feature_hook = [HikingTrailClosuresFeatureHook::class, 'call'];
    $u->feature_init = [HikingTrailClosuresFeatureInit::class, 'call'];
    $u->fetcher = [HikingTrailClosuresFetcher::class, 'call'];
    $u->make_fetch_def = [HikingTrailClosuresMakeFetchDef::class, 'call'];
    $u->make_context = [HikingTrailClosuresMakeContext::class, 'call'];
    $u->make_options = [HikingTrailClosuresMakeOptions::class, 'call'];
    $u->make_request = [HikingTrailClosuresMakeRequest::class, 'call'];
    $u->make_response = [HikingTrailClosuresMakeResponse::class, 'call'];
    $u->make_result = [HikingTrailClosuresMakeResult::class, 'call'];
    $u->make_point = [HikingTrailClosuresMakePoint::class, 'call'];
    $u->make_spec = [HikingTrailClosuresMakeSpec::class, 'call'];
    $u->make_url = [HikingTrailClosuresMakeUrl::class, 'call'];
    $u->param = [HikingTrailClosuresParam::class, 'call'];
    $u->prepare_auth = [HikingTrailClosuresPrepareAuth::class, 'call'];
    $u->prepare_body = [HikingTrailClosuresPrepareBody::class, 'call'];
    $u->prepare_headers = [HikingTrailClosuresPrepareHeaders::class, 'call'];
    $u->prepare_method = [HikingTrailClosuresPrepareMethod::class, 'call'];
    $u->prepare_params = [HikingTrailClosuresPrepareParams::class, 'call'];
    $u->prepare_path = [HikingTrailClosuresPreparePath::class, 'call'];
    $u->prepare_query = [HikingTrailClosuresPrepareQuery::class, 'call'];
    $u->graphql_body = [HikingTrailClosuresGraphql::class, 'body'];
    $u->graphql_errors = [HikingTrailClosuresGraphql::class, 'errors'];
    $u->result_basic = [HikingTrailClosuresResultBasic::class, 'call'];
    $u->result_body = [HikingTrailClosuresResultBody::class, 'call'];
    $u->result_headers = [HikingTrailClosuresResultHeaders::class, 'call'];
    $u->transform_request = [HikingTrailClosuresTransformRequest::class, 'call'];
    $u->transform_response = [HikingTrailClosuresTransformResponse::class, 'call'];
});
